baseURL = ""
languageCode = "nl-NL"
title = "nieuwe-geboorte.nl"
theme = "newbirth"
enableRobotsTXT = true
googleAnalytics = "UA-xxxxx-1"

[outputs]
home = [ "HTML", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffixes = [ "" ]
delimiter = ""

[outputFormats]
  [outputFormats.redirect]
    mediatype = "text/plain"
    baseName = "_redirects"
    isPlainText = true
  [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[params]
  [params.homepage_meta_tags]
    meta_description = ""
    meta_og_title = "De weg naar de Waarheid van de Eeuwige Liefde"
    meta_og_type = "article"
    meta_og_url = "https://nieuwe-geboorte.nl/"
    meta_og_image = "https://nieuwe-geboorte.nl/images/social.png"
    meta_og_description = ""
    meta_og_site_name = "nieuwe-geboorte.nl"
